 # !/usr/bin/env ruby
 # ^syntax detection

source "http://api.berkshelf.com"

# This one is for 512mb instances, or it will crash. 
# Chef-server requires 1GB of ram
#cookbook 'swap',
#    git: 'https://github.com/sethvargo-cookbooks/swap'

cookbook 'chef-client'
cookbook 'apt'
cookbook 'yum'
cookbook 'yum-centos'
cookbook 'yum-epel'
cookbook 'nginx'
cookbook 'vim'
cookbook 'git'
cookbook 'mercurial'
